[versions]
kotlin = "2.3.0"
activityCompose = "1.12.2"
ktor = "3.3.3"
sqldelight = "2.2.1"
testcore = "1.7.0"
documentfile = "1.1.0"
junit = "4.13.2"
kotlinx-atomicfu = "0.29.0"
kotlinx-datetime = "0.7.1"
kotlinx-serialization-encoding = "1.10.0"
kotlinx-coroutines-core = "1.10.2"
kotlinx-browser = "0.5.0"
lifecycleRuntime = "2.10.0"
okio = "3.16.4"
android-compileSdk = "36"
android-minSdk = "28"
testrunner = "1.7.0"
dokka = "2.1.0"
jna = "5.18.1"
dbus-java = "5.2.0"

[libraries]
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
androidx-test-core = { module = "androidx.test:core", version.ref = "testcore" }
androidx-test-runner = { module = "androidx.test:runner", version.ref = "testrunner" }
documentfile = { module = "androidx.documentfile:documentfile", version.ref = "documentfile" }
jna = { module = "net.java.dev.jna:jna", version.ref = "jna" }
jna-platform = { module = "net.java.dev.jna:jna-platform", version.ref = "jna" }
junit = { module = "junit:junit", version.ref = "junit" }
kotlinx-atomicfu = { module = "org.jetbrains.kotlinx:atomicfu", version.ref = "kotlinx-atomicfu" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines-core" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines-core" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization-encoding" }
kotlinx-serialization-cbor = { module = "org.jetbrains.kotlinx:kotlinx-serialization-cbor", version.ref = "kotlinx-serialization-encoding" }
kotlinx-browser = { module = "org.jetbrains.kotlinx:kotlinx-browser", version.ref = "kotlinx-browser" }
ktor-server-core = { module = "io.ktor:ktor-server-core", version.ref = "ktor" }
lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime", version.ref = "lifecycleRuntime" }
okio = { module = "com.squareup.okio:okio", version.ref = "okio" }
sqldelight-runtime = { module = "app.cash.sqldelight:runtime", version.ref = "sqldelight" }
sqldelight-native-driver = { module = "app.cash.sqldelight:native-driver", version.ref = "sqldelight" }
sqldelight-jvm-driver = { module = "app.cash.sqldelight:sqlite-driver", version.ref = "sqldelight" }
sqldelight-android-driver = { module = "app.cash.sqldelight:android-driver", version.ref = "sqldelight" }
dbus-java-core = { module = "com.github.hypfvieh:dbus-java-core", version.ref = "dbus-java" }
dbus-java-transport-native-unixsocket = { module = "com.github.hypfvieh:dbus-java-transport-native-unixsocket", version.ref = "dbus-java" }

[plugins]
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }